### ISSUE TITLE
OS X EI Capitan 10.11.3上安装Nginx+MySQL+PHP

### ISSUE THREAD

**Issue by 2013xile** [Xilesun/blog#1]
前几日在新购的macbook Pro上搭建PHP环境，因为网上提供的资料不够准确，故走了一些弯路，特此记录，以帮助有需要的新手。OS X自带Apache和PHP，这里讲的是使用Nginx服务器。
### 1. 安装brew

brew是OS X上一个优秀的命令行包管理工具，用它来安装一系列软件非常方便。

``` bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
### 2. 安装MySQL

首先我们来安装MySQL，因为它最容易安装

``` bash
brew install mysql
```

安装完成后为MySQL设置密码
首先无密码登录，用户名为root

``` bash
mysql -u root
```

在MySQL中操作

``` bash
>update mysql.user set authentication_string="new password" where User='root'；
>flush privileges；
>quit
```
### 3. 安装PHP

安装PHP7.0

``` bash
brew install homebrew/php/php70 homebrew/php/php70-mcrypt homebrew/php/php70-gmagick homebrew/php/php70-opcache homebrew/php/php70-xdebug
```

接下来在命令行中输入

``` bash
export PATH="/usr/local/sbin:$PATH"  
echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile  
```

最后输入`php -v`和`php-fpm -v`都应该显示PHP版本号7.0.x
### 启动php-fpm

``` bash
sudo php-fpm
```
### 结束php-fpm

``` bash
sudo pkill php-fpm
```

注意在终端中启动php-fpm之后未结束前不要关闭窗口，若输入其他命令应该新建窗口，非正常关闭重新启动将显示端口被占用，此时需要修改默认的端口9000为其他端口。修改方法在介绍完Nginx的安装之后在说明，因为其中涉及到Nginx的相关设置。
### 4. 安装Nginx

最后安装Nginx，这一步有很多关键的设置，务必认真。
安装

``` bash
brew install --with-http2 nginx
```

安装后进行相关设置，打开设置文件

``` bash
vim /usr/local/etc/nginx/nginx.conf
```

根据需要做如下修改

``` bash
server {
    listen       8080; #默认端口为8080
    server_name  localhost; #网站地址

    #charset koi8-r;

    #access_log  logs/host.access.log  main;

    #如果想使用80端口，需要给予权限，添加下面两行并参考下一个步骤，不需要则可以跳过
    ssl_certificate ssl/nginx.crt;
    ssl_certificate_key ssl/nginx.key;

    location / {
        root   html; #html为网站根目录，可以自己修改
        index  index.html index.htm; #添加index.php
    }
```

生成密钥给予权限以使用80端口

``` bash
sudo mkdir /usr/local/etc/nginx/ssl/  
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /usr/local/etc/nginx/ssl/nginx.key -out /usr/local/etc/nginx/ssl/nginx.crt
```

设置Nginx支持php
在刚才的配置文件中找到以下几行，去掉前面的井号，即使注释内容生效。并做相应修改

``` bash
location ~ \.php$ {
    root           html; #此处的根目录应与上面的设置的一致
    fastcgi_pass   127.0.0.1:9000; #此处可以设置php-fpm默认端口
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name; #此处将/scripts$fastcgi_script_name修改为根目录$fastcgi_script_name
    include        fastcgi_params; #将此行代码与上一行对调位置
}
```

至此设置完成。
### 启动Nginx

``` bash
sudo nginx
```
### 结束/重载（配置文件）Nginx

``` bash
sudo nginx -s stop/reload
```
### 关于修改php-fpm默认端口的说明

在前面Nginx配置文件注释中已经有提到一处php-fpm默认端口的修改，这是在Nginx中进行设置，接下来只需在php-fpm的配置文件中另外修改即可。文件路径`/usr/local/etc/php/7.0/php-fpm.d/www.conf`，在文件中找到`listen = 127.0.0.1:9000`进行修改即可。

参考资料：
[http://wlkns.co/install-nginx-php-mysql-on-mac-osx/](http://wlkns.co/install-nginx-php-mysql-on-mac-osx/)  
[http://yangtai.blog.51cto.com/334569/213861](http://yangtai.blog.51cto.com/334569/213861)

**Comment by hogin** [comment]
非常感谢,感觉很好用，但是mysql换密码之后就登陆不进去了，后来重装了。

**Comment by namespacegit** [comment]
非常感谢,感觉很好用，但是mysql换密码之后就登陆不进去了，后来重装了。

**Comment by jerome-ss** [comment]
非常感谢,感觉很好用，但是mysql换密码之后就登陆不进去了，后来重装了。

**Comment by PekingStreet** [comment]
步骤二  安装Mysql后，mysql并未启动，需要先启动：brew services start mysql

**Comment by yoyo0926** [comment]
可以安装多版本的php共存吗？有的程序还不支持7.0需要5.6的怎么办，谢谢

**Comment by hogin** [comment]
在本地你可以安装多个版本的php，看你用哪一个

**Comment by 2013xile** [comment]
@yoyo0926 如果需要多版本的话你可以用docker调试，我感觉比较方便。如果是程序只支持5.6的话，你就安装5.6不安装7.0，网上也蛮多教程参考。

**Comment by zetttt** [comment]
mysql修改密码那里应该是:
update mysql.user set authentication_string=password('new password') where user='root';

其实安装完mysql后，直接执行 mysql_secure_installation，按步骤配置密码和其他安全项比较好。

**Comment by vivalee** [comment]
指出小小的问题，Mysql修改密码>update mysql.user set authentication_string=PASSWORD("new password") where User='root'；必须调用mysql的PASSWORD函数把密码包起来。
fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name; 替换成fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;其它位置啥的不变，我的安装环境是这样才过的，不然找不到文件

**Comment by hogin** [comment]
更改了nginx后应该还需要改hosts文件吧，将域名添加进去，然后才能访问。
